### ISSUE TITLE
Error message on launching installer

### ISSUE THREAD

**Issue by thechordmaster** [Chax1/VRPE-Installer#16]
---------------------------
Error during runtime!
---------------------------
Exception Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 4x.xx.xx.xxx:443

Please post your issue here: https://github.com/Chax1/VRPE-Installer/issues or contact Chax#1337 on Discord
---------------------------
OK   
---------------------------

Any idea why this happens?

**Comment by Chax1** [comment]
Issue was fixed, user was using a weird DNS Setup that caused raw.githubusercontent.com to time out and therefore break the program.
