### ISSUE TITLE
No 32bits (Win10) support anymore?

### ISSUE THREAD

**Issue by RobH0206** [Chax1/VRPE-Installer#17]
Hi Chax1, tried to install the VRP Essential package, but it complains after install on my 32bit Win10 machine?
 
![Screenshot 2023-01-17 181050](https://user-images.githubusercontent.com/122913296/212965863-f9b63efb-9fa8-45a6-bebf-323a69e2874e.png)

Is this correct and is 32 bits not supported anymore?

Hope to hear soon!

**Comment by Chax1** [comment]
I'm looking into the issue, for the meanwhile just open the path Rookie was downloaded into and then open the exe there manually.

**Comment by Chax1** [comment]
I've updated the current binary, please try this again and report back if it works or not.

**Comment by RobH0206** [comment]
Redownloaded and the issue persists unfortunately...

**Comment by RobH0206** [comment]
> I'm looking into the issue, for the meanwhile just open the path Rookie was downloaded into and then open the exe there manually.

This does not work either by the way!

**Comment by Chax1** [comment]
> > I'm looking into the issue, for the meanwhile just open the path Rookie was downloaded into and then open the exe there manually.
> 
> This does not work either by the way!

Can you replace the exe with this one?
[AndroidSideloader_v2.18.zip](https://github.com/Chax1/VRPE-Installer/files/10438054/AndroidSideloader_v2.18.zip)

**Comment by Chax1** [comment]
Closing issue due to lack of response.

**Comment by RobH0206** [comment]
Good morning Chax1. Apologies for the delay, but in my timezone it was night and I wanted to pick this up again in the morning. I just checked the zip file and tried to run on my PC, but it is not letting me do it.

![Screenshot 2023-01-18 111304](https://user-images.githubusercontent.com/122913296/213144813-e55cae2d-7a4b-4878-811a-917b73bcead0.png)

Kindly request to reopen the issue and find a solution to my problem.

**Comment by Chax1** [comment]
> Good morning Chax1. Apologies for the delay, but in my timezone it was night and I wanted to pick this up again in the morning. I just checked the zip file and tried to run on my PC, but it is not letting me do it.
> 
> ![Screenshot 2023-01-18 111304](https://user-images.githubusercontent.com/122913296/213144813-e55cae2d-7a4b-4878-811a-917b73bcead0.png)
> 
> Kindly request to reopen the issue and find a solution to my problem.
> 
>  

Thats really confusing, that exe is compiled for both 32 Bit and 64 Bit so its supposed to run, make sure your Windows Defender and Smartscreen isnt blocking anything.

**Comment by Chax1** [comment]
Also are you running a native Windows 10 Install or is this Virtualized like Parellels on M1/M2 Macs?

**Comment by RobH0206** [comment]
This is a native Win 10 install.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RobH0206** [comment]
Will try that later today... Apologies for the confusion.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RobH0206** [comment]
Switched off all Smartscreen and Defender entries and retried to install the extracted zip file sent earlier. Same error message and hence the same problem for my PC unfortunately.

**Comment by Chax1** [comment]
Im gonna look into this in a second once im home.

**Comment by Chax1** [comment]
I may have found the issue, please try this exe. 
[AndroidSideloader_v2.18.zip](https://github.com/Chax1/VRPE-Installer/files/10446289/AndroidSideloader_v2.18.zip)

**Comment by RobH0206** [comment]
Also on the road. Will try this once I get home as well.



Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by RobH0206** [comment]
We are making progress. But still not without errors.

![Screenshot 2023-01-18 163351](https://user-images.githubusercontent.com/122913296/213215018-50d58f80-2de7-45c2-8451-eba6955f9dd3.png)

And then...

![Screenshot 2023-01-18 163439](https://user-images.githubusercontent.com/122913296/213215067-c565daa9-fecd-43d8-95ba-cdb1f5e22013.png)

End result is that Rookie is launched, but then there is an exception handler thrown. Clicking Continue then kills the application...

Also my anti virus is reporting a virus is detected in the zip file you just sent... for what it is worth...

**Comment by Chax1** [comment]
I think I know whats going on, while I did fix the compile of Rookie itself, it uses 7z to extract the ADB it downloads, however I believe the 7z exe it uses is not 32 Bit therefore it will not work and Rookie will always crash, I cannot just easily fix this therefore I am closing this issue as not planned.

I will look into it and give it a try to fix it, however there are no promises, you can use Resilio + Sidenoder as an alternative until then.

**Comment by RobH0206** [comment]
Thanks fir explaining. Are you referring to 7-Zip as the application to extract the ADB? I know that exists in a 32 bits application. How hard would it be to include the 32 bit version as well and instruct it accordingly to be used in installations on 32 bits platforms?

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
