### ISSUE TITLE
VRPE Installer Display

### ISSUE THREAD

**Issue by coolrabbitman** [Chax1/VRPE-Installer#18]
![Screenshot 2023-03-06 124409](https://user-images.githubusercontent.com/108051259/223021327-be25f6d2-f8f4-434d-8436-eaacce588ae2.png)

I tried maximizing the window by pressing f11, alt + enter, and windows + up but the display still doesn't seem to be working correctly

**Comment by Chax1** [comment]
Hey thanks for writing an issue post, can you check if your Display is scaling anything?

You can check this in the Windows Settings under Display and then "Scale"

![image](https://user-images.githubusercontent.com/69131569/223121482-8c135335-66bc-4bda-a96c-06a9d365e25d.png)

**Comment by coolrabbitman** [comment]
![image](https://user-images.githubusercontent.com/108051259/223127693-18edd7f2-6818-49ec-9e75-45ab570bbefe.png)
OH yeah I was at 125% before and when I put it to 100% the window displays correctly now!
![image](https://user-images.githubusercontent.com/108051259/223128201-19291d55-5d97-41b2-8bc7-e819ee1b65f2.png)
tysm!

**Comment by Chax1** [comment]
Hey thanks for bringing this to my attention, yes setting your scaling to 100% fixes the problem but it should work on any scaling, which I've now fixed.

I've updated the binary with a fixed one.
