### ISSUE TITLE
im having issues 

### ISSUE THREAD

**Issue by danrog5050** [Chax1/VRPE-Installer#22]
im having issues using this app its saying
Exception Message: Could not find a part of the path
after i hit ok the app wont connect to the servers and keeps trying to put me in offline mode what do i do to fix this

**Comment by Arkannax** [comment]
I am having this same issue. 

When I launch Rookie, it forces me to launch in offline mode also.

Ive additionally downloaded VRP-GUI.
However, "VRP-GUI Essentials" folder does not exist to move any config files.

Everything is in the RSL folder that auto-created in C: upon download, Ive removed that RSL folder in C:drive from the virus & threat scan.

I opened task manager and "Rsync for rclone" is not running either.
I even tried to install and move everything to D: drive, but uninstalled and left it local as it was autoinstalling.


![Drive C](https://user-images.githubusercontent.com/107443482/227793206-e1c501f7-749c-436b-9db0-ce9d19b1b9d9.PNG)
![Sideloader 2 19 launch](https://user-images.githubusercontent.com/107443482/227793208-d8d245bf-28b1-46e3-b329-7d82ba7ff2ae.PNG)
![Sideloader game list](https://user-images.githubusercontent.com/107443482/227793209-8c0cd4a3-6114-4096-8be8-8b493b056540.PNG)
![Virus removal](https://user-images.githubusercontent.com/107443482/227793210-9a73ff88-3557-490e-8006-02d8d7613e55.PNG)

**Comment by Chax1** [comment]
Heya, I think I identified the issue and will be working promptly to fix it.

**Comment by Chax1** [comment]
Actually I think it might be that you guys still have older versions of the VRPE, could you please attempting the newest version and trying from there? :)

**Comment by Chax1** [comment]
I will be implementing an updater to solve issues like these.

**Comment by Chax1** [comment]
By the screenshot provided by @Arkannax it looks like you guys are on the VRPE 1.3 which still just unzips the given Rookie Link which when it doesn't have a prepackaged folder it fails to do it properly, it also has old launch methods implemented which use a different path than the VRPE 1.4 which launches properly.

**Comment by Chax1** [comment]
After jumping back a few versions, my suspicion is confirmed.
![image](https://user-images.githubusercontent.com/69131569/227802805-a6ee5b62-5dd4-48b7-b2d3-90a3c8877311.png)
This is what happens on 1.2
while it works properly on 1.4

Thanks for bringing this issue to my attention, for the meanwhile both of you should update the VRPE, I will be implementing an updater, thank you!

**Comment by danrog5050** [comment]
Awesome thanks

**Comment by Chax1** [comment]
Update is out: https://github.com/Chax1/VRPE-Installer/releases/tag/v1.5

**Comment by danrog5050** [comment]
Still not working

**Comment by danrog5050** [comment]
![20230326_164457](https://user-images.githubusercontent.com/128989257/227806914-4b9ab435-7dfb-465d-afe2-b0aac3e32f9e.jpg)
![20230326_164921](https://user-images.githubusercontent.com/128989257/227806915-cf18f337-15d4-41e3-8054-7601a64b378f.jpg)
![20230326_162547](https://user-images.githubusercontent.com/128989257/227806916-76192e5c-c8ae-4600-8e34-7d104492cf8a.jpg)

**Comment by Chax1** [comment]
Yeah thats Rookie not working, our servers are currently down, nothing to do with VRPE, sorry.

**Comment by danrog5050** [comment]
Alright no problem just was making sure I did everything right and didn't
mess up anything during install and setup. Lol
