### ISSUE TITLE
Please help me this issue

### ISSUE THREAD

**Issue by Lilgirl2023** [Chax1/VRPE-Installer#24]
I installed the app but got the error message. What should I do? I tried to uninstall and install many times, use different locations to install but always get the same errors:

---------------------------
Error during runtime!
---------------------------
Exception Message: Could not find a part of the path 'C:\Users\nhufi\AppData\Local\Microsoft\XboxLive\rookie_2.19_portable'.

Please post your issue here: https://github.com/Chax1/VRPE-Installer/issues or contact Chax#1337 on Discord

**Comment by Chax1** [comment]
Please update the VRPE :)
