### ISSUE TITLE
Rookie install

### ISSUE THREAD

**Issue by Arctiv** [Chax1/VRPE-Installer#26]
Trying to install Rookie through VRPE gave me this message:
Error during runtime!
Exception Message: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

Please help

**Comment by Chax1** [comment]
I've updated the binary on the repository, please redownload the VRPE and try again.

**Comment by Arctiv** [comment]
It worked, thank you so much!
