### ISSUE TITLE
my error

### ISSUE THREAD

**Issue by yaricark123** [Chax1/VRPE-Installer#28]
---------------------------
Error during runtime!
---------------------------
Exception Message: Запрос был прерван: Не удалось создать защищенный канал SSL/TLS.

Please post your issue here: https://github.com/Chax1/VRPE-Installer/issues
---------------------------
OK   
---------------------------

**Comment by Chax1** [comment]
Not an issue with my program but rather your internet, sorry, try getting a secure connection via a VPN.
