### ISSUE TITLE
Exception message : Méthode introuvable : 'Int32 System.Windows.Forms.Control.get_DeviceDpi()'.

### ISSUE THREAD

**Issue by Lort0m** [Chax1/VRPE-Installer#31]
I got this message and i try to reopen it with my anti-virus off but it doesn't work
![image](https://github.com/Chax1/VRPE-Installer/assets/133520966/a1248870-5d42-4951-849a-7ceacc451a46)

**Comment by frxctura** [comment]
Reinstall the program.
This is not an application issue but more so a Windows issue.

**Comment by Lort0m** [comment]
I reinstall it but i got the same message

**Comment by Lort0m** [comment]
Nvm it worked thx
