### ISSUE TITLE
Should I allow this? The wiki says that there are false positives if you aren't using windows defender, and I am.

### ISSUE THREAD

**Issue by BraydenGamelover** [Chax1/VRPE-Installer#32]
![image](https://github.com/Chax1/VRPE-Installer/assets/121322972/44307ab2-6d29-40e5-9eb9-9b6c0d1d5fb6)
![image](https://github.com/Chax1/VRPE-Installer/assets/121322972/92a322ee-2309-4c18-9532-364d0b0150ba)

**Comment by frxctura** [comment]
Even Windows Defender will false flag this, in the end youre free to pick what you wanna allow but the source code is open and compileable.

The VRPE just gets heavily flagged due to it:

- Downloading files
- Extracting files
- Moving files
- Running files
- Creating and writing to files

**Comment by BraydenGamelover** [comment]
Thank you.

**Comment by frxctura** [comment]
> Thank you.

Youre welcome :)
